// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC9N6d9O7fXa55slwgEbQDc94I4StYNQO0',
    appId: '1:602471582725:web:20c88488e82f8d0c5a206c',
    messagingSenderId: '602471582725',
    projectId: 'eventsphere-9edf8',
    authDomain: 'eventsphere-9edf8.firebaseapp.com',
    databaseURL: 'https://eventsphere-9edf8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'eventsphere-9edf8.firebasestorage.app',
    measurementId: 'G-QW8X6D92P2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCak5fxL3zKEUZF70mKuVFcSGn07sOWwAY',
    appId: '1:602471582725:android:39fc18e939eed6235a206c',
    messagingSenderId: '602471582725',
    projectId: 'eventsphere-9edf8',
    databaseURL: 'https://eventsphere-9edf8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'eventsphere-9edf8.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDgi0cQi6WDKvAQWOLR68MyFS12vxyY9oc',
    appId: '1:602471582725:ios:7f0427774f7c6ca05a206c',
    messagingSenderId: '602471582725',
    projectId: 'eventsphere-9edf8',
    databaseURL: 'https://eventsphere-9edf8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'eventsphere-9edf8.firebasestorage.app',
    iosBundleId: 'com.example.event',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDgi0cQi6WDKvAQWOLR68MyFS12vxyY9oc',
    appId: '1:602471582725:ios:7f0427774f7c6ca05a206c',
    messagingSenderId: '602471582725',
    projectId: 'eventsphere-9edf8',
    databaseURL: 'https://eventsphere-9edf8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'eventsphere-9edf8.firebasestorage.app',
    iosBundleId: 'com.example.event',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyC9N6d9O7fXa55slwgEbQDc94I4StYNQO0',
    appId: '1:602471582725:web:bfe196177d3d63f95a206c',
    messagingSenderId: '602471582725',
    projectId: 'eventsphere-9edf8',
    authDomain: 'eventsphere-9edf8.firebaseapp.com',
    databaseURL: 'https://eventsphere-9edf8-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'eventsphere-9edf8.firebasestorage.app',
    measurementId: 'G-2DW3PJG3SS',
  );
}
